package com.keda.minidao.entity;

// Generated 2018-6-7 15:13:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WmsStockAdjust generated by hbm2java
 */
public class WmsStockAdjust implements java.io.Serializable {

	private Integer id;
	private String createName;
	private String createBy;
	private Date createDate;
	private String updateName;
	private String updateBy;
	private Date updateDate;
	private String sysOrgCode;
	private String sysCompanyCode;
	private String bpmStatus;
	private String goodsno;
	private String goodsname;
	private String lotno;
	private String orglocno;
	private String orgzoneno;
	private String stockqty;
	private String newlocno;
	private String newzoneno;
	private String adjstatus;
	private Integer orglayer;
	private Integer newlayer;

	public WmsStockAdjust() {
	}

	public WmsStockAdjust(String createName, String createBy, Date createDate,
			String updateName, String updateBy, Date updateDate,
			String sysOrgCode, String sysCompanyCode, String bpmStatus,
			String goodsno, String goodsname, String lotno, 
			String orglocno,String orgzoneno,String stockqty,
			String newlocno,String newzoneno,String adjstatus,
			Integer orglayer,Integer newlayer){
		this.createName = createName;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateName = updateName;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.sysOrgCode = sysOrgCode;
		this.sysCompanyCode = sysCompanyCode;
		this.bpmStatus = bpmStatus;
		this.goodsno = goodsno;
		this.goodsname = goodsname;
		this.lotno = lotno;
		this.orglocno = orglocno;
		this.orgzoneno = orgzoneno;
		this.stockqty = stockqty;
		this.newlocno = newlocno;
		this.newzoneno = newzoneno;
		this.adjstatus = adjstatus;
		this.orglayer = orglayer;
		this.newlayer = newlayer;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCreateName() {
		return this.createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUpdateName() {
		return this.updateName;
	}

	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getSysOrgCode() {
		return this.sysOrgCode;
	}

	public void setSysOrgCode(String sysOrgCode) {
		this.sysOrgCode = sysOrgCode;
	}

	public String getSysCompanyCode() {
		return this.sysCompanyCode;
	}

	public void setSysCompanyCode(String sysCompanyCode) {
		this.sysCompanyCode = sysCompanyCode;
	}

	public String getBpmStatus() {
		return this.bpmStatus;
	}

	public void setBpmStatus(String bpmStatus) {
		this.bpmStatus = bpmStatus;
	}

	public String getGoodsno() {
		return this.goodsno;
	}

	public void setGoodsno(String goodsno) {
		this.goodsno = goodsno;
	}

	public String getGoodsname() {
		return this.goodsname;
	}

	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	public String getLotno() {
		return this.lotno;
	}

	public void setLotno(String lotno) {
		this.lotno = lotno;
	}

	public String getOrglocno() {
		return orglocno;
	}

	public void setOrglocno(String orglocno) {
		this.orglocno = orglocno;
	}

	public String getOrgzoneno() {
		return orgzoneno;
	}

	public void setOrgzoneno(String orgzoneno) {
		this.orgzoneno = orgzoneno;
	}

	public String getStockqty() {
		return stockqty;
	}

	public void setStockqty(String stockqty) {
		this.stockqty = stockqty;
	}

	public String getNewlocno() {
		return newlocno;
	}

	public void setNewlocno(String newlocno) {
		this.newlocno = newlocno;
	}

	public String getNewzoneno() {
		return newzoneno;
	}

	public void setNewzoneno(String newzoneno) {
		this.newzoneno = newzoneno;
	}

	public String getAdjstatus() {
		return adjstatus;
	}

	public void setAdjstatus(String adjstatus) {
		this.adjstatus = adjstatus;
	}

	public Integer getOrglayer() {
		return orglayer;
	}

	public void setOrglayer(Integer orglayer) {
		this.orglayer = orglayer;
	}

	public Integer getNewlayer() {
		return newlayer;
	}

	public void setNewlayer(Integer newlayer) {
		this.newlayer = newlayer;
	}

	
}
